= Common Blueprints 

== Packages

== Partitioning

By default *Fedora Minimal* uses raw partitioning with an `ext4` root partition mounted at `/`. This can be changed in the following ways. If you want to know more about partitioning and how it behaves you can read the https://osbuild.org/docs/user-guide/partitioning/[upstream documentation] for `image-builder`.

=== btrfs

To build an image that uses btrfs you can use the following blueprint. This mimicks the Fedora Workstation subvolumes.

[source,toml]
----
[[customizations.disk.partitions]]
type = "btrfs"
minsize = "3 GiB"
subvolumes = [
  { name = "root", mountpoint = "/" },
  { name = "home", mountpoint = "/home" },
]
----

It can be wise to also have `/var` on a separate subvolume.

=== lvm

To build an image that uses LVM:

[source,toml]
----
[[customizations.disk.partitions]]
type = "lvm"
minsize = "3 GiB"
----

This will convert the partition that contains the root mountpoint `/` to an LVM Volume Group containing a root Logical Volume.

== Users

You can add, or modify users in the image you are building with the `users` customization. Users are identified by name. If the user already exists (for example, because one of the packages you installed created the user) it will be modified. If the user doesn't exist it will be created.

[source,toml]
----
[[customizations.users]]
name = "myuser"
key = "ssh-ed25519 AAxxxAA user@host"
----

Will create or update the user by the name of `myuser` setting their SSH authorized keys to the given key. For more options read the https://osbuild.org/docs/user-guide/blueprint-reference/#additional-users[upstream documentation] for `image-builder`.
